### PR TITLE
Adding the paginator changes which were requested

### PR DESCRIPTION
**Pull request by aadi58002**
solving #24

### CODE REVIEW

**Review by ashutoshkrris — CHANGES_REQUESTED** [review]
Looks good, but still few things aren't resolved:

1. The elided pages are not shown.
Screenshot 2022-10-20 225338
In the above image, we can see that some page numbers from the beginning are shown, then ... is shown and then few page numbers from the end are shown. Note that all these page numbers are clickable.

3. The mouse hover doesn't get changed to cursor.

**Comment by aadi58002** [comment]
> Looks good, but still few things aren't resolved:
> 
> 1. The elided pages are not shown.
>    Screenshot 2022-10-20 225338
>    In the above image, we can see that some page numbers from the beginning are shown, then ... is shown and then few page numbers from the end are shown. Note that all these page numbers are clickable.
> 2. The mouse hover doesn't get changed to cursor.

Ok that should do all the changes. I also merged all the changes into one commit so it should be all in this one pull request.
Thanks for pointing out the changes again specifically after i forgot them

**Review by ashutoshkrris — CHANGES_REQUESTED** [review]
Could you look into the mobile version? Things don't look well there

**Review by ashutoshkrris — CHANGES_REQUESTED** [review]
Could you please reduce the spacing between them? It would be better to have half the spacing.
Screenshot 2022-10-21 002913

Also, I see the page numbers are getting hidden in the mobile version. Isn't it possible to show them as in the web version?
Screenshot 2022-10-21 003020

**Comment by aadi58002** [comment]
I will complete them in the morning it is night time here. I really appreciate you bringing these changes to me . Thanks for quick responses

**Comment by ashutoshkrris** [comment]
> I will complete them in the morning it is night time here. I really appreciate you bringing these changes to me . Thanks for quick responses

Thanks to you for working on these.

**Pull request closed without merging**
