### PR TITLE
I have added bottom to top button with all html,css and js codes. Kindly check it.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ashutoshkrris** [comment]
Hi @Igdtuwresource 
This is a Vue.js project, so you need to create the button as per Vue.js.

**Comment by ghost** [comment]
Oh okay. I will try it again.

**Comment by ghost** [comment]
@ashutoshkrris I have updated the button now. Kindly review.

**Comment by ashutoshkrris** [comment]
The button doesn't work as expected.

**Comment by ghost** [comment]
@ashutoshkrris my PR got merged, so will it be included in hacktober fest?

**Comment by ashutoshkrris** [comment]
Yes, it should be.
Please check in your Hacktoberfest profile.

**Comment by ghost** [comment]
image
it's showing me this

**Comment by ghost** [comment]
@ashutoshkrris

**Comment by ashutoshkrris** [comment]
Please wait for some time to get the updated status.

**Pull request merged**
