### PR TITLE
Responsive for Mobile screen.

### LINKED ISSUE #45: [Bug]: Minor bugs in pagination component
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Current Behavior

Currently, the pagination is working fine. But there are a few minor bugs that need to be resolved:

* When the pagination component first loads up, only the Previous and Next buttons are there.
Screenshot 2022-12-31 005602

* Make it responsive (mobile-friendly)
Screenshot 2022-12-31 005644

### Expected Behavior

The above problems need to be resolved

### To Reproduce

* Go to the deployed web app here: https://techywrite.vercel.app/
* See the problems

### Anything else?

If you see any more bugs related to pagination, do mention it here.

### Hacktoberfest

- [ ] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Rishav1707**
# Description

Fixes #45 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests/screenshots(if any) that prove my fix is effective or that my feature works

# Screenshots
Responsive

### CODE REVIEW

**Review by ashutoshkrris — COMMENTED** [review]
Hi @Rishav1707 
Thank you for making the PR.
But, issue #45 was related to just the pagination component, and the PR doesn't make any change to that.

**Comment by Rishav1707** [comment]
> Hi @Rishav1707 Thank you for making the PR. But, issue #45 was related to just the pagination component, and the PR doesn't make any change to that.

Also in issue #45 it mention about responsive for mobile screen.
I am only worked on responsiveness in mobile screen that's why I requested this PR.

**Comment by ashutoshkrris** [comment]
> > Hi @Rishav1707 Thank you for making the PR. But, issue #45 was related to just the pagination component, and the PR doesn't make any change to that.
> 
> Also in issue #45 it mention about responsive for mobile screen. I am only worked on responsiveness in mobile screen that's why I requested this PR.

That responsiveness was also related to pagination component actually.

**Comment by Rishav1707** [comment]
> > > Hi @Rishav1707 Thank you for making the PR. But, issue #45 was related to just the pagination component, and the PR doesn't make any change to that.
> > 
> > 
> > Also in issue #45 it mention about responsive for mobile screen. I am only worked on responsiveness in mobile screen that's why I requested this PR.
> 
> That responsiveness was also related to pagination component actually.

Ok I will try to solve it...

**Comment by Rishav1707** [comment]
> > > Hi @Rishav1707 Thank you for making the PR. But, issue #45 was related to just the pagination component, and the PR doesn't make any change to that.
> > 
> > 
> > Also in issue #45 it mention about responsive for mobile screen. I am only worked on responsiveness in mobile screen that's why I requested this PR.
> 
> That responsiveness was also related to pagination component actually.

Done @ashutoshkrris

**Comment by ashutoshkrris** [comment]
Did you delete the `OpportunityList.vue` file?

**Comment by Rishav1707** [comment]
> Did you delete the `OpportunityList.vue` file?

Yes, because I only want to commit style.css file

**Comment by Rishav1707** [comment]
> Did you delete the `OpportunityList.vue` file?

Sorry, by mistake it was deleted.
But I recovered it...

**Comment by Rishav1707** [comment]
@ashutoshkrris Please review my changes...

**Comment by Rishav1707** [comment]
> @ashutoshkrris Please review my changes...

?? @ashutoshkrris

**Review by ashutoshkrris — CHANGES_REQUESTED** [review]
Hi @Rishav1707 
The mobile version still doesn't look as expected.
Screenshot_2023-01-08-10-23-13-736_com android chrome

**Comment by Rishav1707** [comment]
> Hi @Rishav1707 The mobile version still doesn't look as expected. Screenshot_2023-01-08-10-23-13-736_com android chrome

I think you have deployed the wrong link...
Screenshot_2023-01-08-10-25-54-27_40deb401b9ffe8e1df2f1cc5ba480b12
See above it's quite better now for mobile screen

**Comment by ashutoshkrris** [comment]
> > Hi @Rishav1707 The mobile version still doesn't look as expected. Screenshot_2023-01-08-10-23-13-736_com android chrome
> 
> I think you have deployed the wrong link... Screenshot_2023-01-08-10-25-54-27_40deb401b9ffe8e1df2f1cc5ba480b12 See above it's quite better now for mobile screen

Could you try going to page number 4?

**Comment by Rishav1707** [comment]
> > > Hi @Rishav1707 The mobile version still doesn't look as expected. Screenshot_2023-01-08-10-23-13-736_com android chrome
> > 
> > 
> > I think you have deployed the wrong link... Screenshot_2023-01-08-10-25-54-27_40deb401b9ffe8e1df2f1cc5ba480b12 See above it's quite better now for mobile screen
> 
> Could you try going to page number 4?

Yaah now I see changes

**Comment by Rishav1707** [comment]
Ok trying to fix this soon...

**Comment by Rishav1707** [comment]
resp

How's this?

**Comment by ashutoshkrris** [comment]
Hi @Rishav1707 
Since I changed the way pagination was working, there's no need to make any changes now in terms of responsiveness

**Pull request closed without merging**
