### PR TITLE
implemented search bar

### LINKED ISSUE #4: Add search functionality
Users should be able to search for opportunities using the name and the categories.

### PR DESCRIPTION
**Pull request by TsarPrince**
This PR fixes #4 

A video demonstration of changes made. I have made sure that I haven't broken any previous functionalities (tested the sorting one and total counts)

https://user-images.githubusercontent.com/31801256/196761795-0bd5816e-232e-4d66-b81c-d231fff88868.mp4

### CODE REVIEW

**Comment by TsarPrince** [comment]
Also tested for mobile responsiveness.
image

**Review by ashutoshkrris — CHANGES_REQUESTED** [review]
Hi @TsarPrince, this looks great!
However, a few changes are required:

1. Could you work on removing this white thing at the bottom?
Screenshot 2022-10-19 231748

2. Could you align the search bar with the card border below?
Screenshot 2022-10-19 232030

3. We also need to search using the categories, please add that too.

4. The `Ctrl+/` thing doesn't work for me. Is it working for you?

**Comment by TsarPrince** [comment]
1. Extended page height
Screenshot (280)

2. Aligned
3. Added categories array
Screenshot (279)
4. Opening a new issue for it.

**Comment by TsarPrince** [comment]
Let me know of any other changes required.

**Comment by ashutoshkrris** [comment]
Just a small enhancement
When no result is found, can we show a message for it with an image, may be?
What do you think? @TsarPrince 
If you want, you can create a separate issue for this.

**Comment by TsarPrince** [comment]
Oh nice, that will be a lot realistic. Working on it 👍

**Pull request merged**
