### PR TITLE
Added svg img and a related message for "no results found"

### LINKED ISSUE #15: [feature request]: Show a message if no results found
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Describe the feature.

The page looks a bit empty when no data is found for a given user query.
Screenshot (280)

### Problem/Motivation.

Missing proper message.

### Possible Solution/Pitch.

Dispaly an image with a "no results found" message for such scenarios.

### Anything else?

_No response_

### Hacktoberfest

- [X] Yeah

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by TsarPrince**
Attempts to fix #15 

## Mobile view
image

## Desktop view
screencapture-127-0-0-1-5173-2022-10-20-15_15_56

### CODE REVIEW

**Comment by ashutoshkrris** [comment]
Hi @TsarPrince 
Could you please resolve the merge conflict?

**Comment by TsarPrince** [comment]
Yes I am looking at it, seems like my code editor has just added spaces here and there and broken big lines to small ones 😑. Causing this merge conflict. Should I pull from main and add my changes back as there was quite little change in lines.

**Comment by ashutoshkrris** [comment]
Yes, pull the latest changes from the remote branch.

**Comment by TsarPrince** [comment]
Sorry it was looking very cumbersome, I have created another PR for this.

**Comment by TsarPrince** [comment]
> added spaces here and there and broken big lines to small ones 😑

@ashutoshkrris seems, like this was done by someone else's code editor. Personally speaking these large splitted lines of code doesn't look very clean to me. However I have pulled this and created another PR.

image

**Pull request closed without merging**
